/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extendedProductPassportSol from "./ExtendedProductPassport.sol";
export type { extendedProductPassportSol };
export type { ComplexManagement } from "./ComplexManagement";
export type { Geolocation } from "./Geolocation";
export type { ProductPassport } from "./ProductPassport";
